import Sidebar from "@/components/global/Sidebar";
import "./globals.css";
import ThemeProvider from "@/components/theme/ThemeProvider";
import { Plus_Jakarta_Sans } from "next/font/google";
import Topbar from "@/components/global/Topbar";
import MainContent from "@/components/global/MainContent";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Oshofree Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={plusJakartaSans.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="transition-all duration-200 ease-linear">
            <div className="flex h-[100dvh] bg-slate-100 dark:bg-zinc-900">
              <div className="hidden w-72 min-w-max shrink-0 flex-col rounded-r-[30px] bg-white pb-3 shadow-sidebar dark:bg-zinc-800 dark:shadow-zinc-950 lg:flex">
                <Sidebar />
              </div>
              <MainContent>
                <Topbar />
                <section className="p-3 sm:p-7">{children}</section>
              </MainContent>
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
